### ISSUE TITLE
Typo in line #2 in README.md

### ISSUE THREAD

**Issue by aniketk21** [kivy-garden/garden.recycleview#26]
Line number 2 in README.md reads:
RecycleView is a Kivy widget that **want** to replace the current ListView. The goal is to have an API that is easy to use, understand, and works within Kv.

Should it be:
1. RecycleView is a Kivy widget that  **wants** to replace the current ListView. The goal is to have an API that is easy to use, understand, and works within Kv.

OR
2. RecycleView is a Kivy widget **with which we want** to replace the current ListView. The goal is to have an API that is easy to use, understand, and works within Kv.

I'm new to Kivy. @tito I'd like to correct this error.

**Comment by tito** [comment]
Hi @aniketmkulkarni . You can click on the fork button, edit the README.md, commit it. Then get back here, and you'll be able to propose a Pull Request. And you're changed will be reflected on the repository, with you as an author of the changes.

Don't hesitate to look at https://help.github.com/articles/using-pull-requests/ for more help :)

**Comment by aniketk21** [comment]
@tito I've already set up the development environment.
What should I replace **want** with?
Option 1 or 2? I think the second one is better.

**Comment by tito** [comment]
The first one i guess :)

**Comment by aniketk21** [comment]
Ok..thanks!

**Comment by dessant** [comment]
Fixed in https://github.com/kivy/kivy/pull/4082.
