### ISSUE TITLE
Control recycleview with keyboard ?

### ISSUE THREAD

**Issue by karlitos** [kivy-garden/garden.recycleview#6]
I am quite excited about the recycleview. I wonder if there is any possibility to control the movement of the view with a keyboard ? I would like to use it as a menu, where I can move the view one entry up/down  on a keypress and select one (e.g. the one in the middle) by hitting enter.

**Comment by tito** [comment]
I don't think this is something that RV should deal with. Keyboard control in a toolkit must more be exposed from the root, with element to Focus. This part is already an issue in Kivy, RV wont be able to resolve it by itself :)

But if you are using RV as a menu, then up to you to implement that specific behavior :)
